# NixOS configuration for milo (home server)
{ config, pkgs, lib, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Base system configuration
    ../../modules/nixos/common.nix
    ../../modules/nixos/users.nix

    # Services - comment out what you don't want yet
    # ../../modules/nixos/services/jellyfin.nix
    # ../../modules/nixos/services/navidrome.nix
    # ../../modules/nixos/services/syncthing.nix
    # ../../modules/nixos/services/docker.nix

    # Networking
    # ../../modules/nixos/networking/tailscale.nix
    # ../../modules/nixos/networking/caddy.nix  # Uncomment when you're ready to set up reverse proxy
  ];

  # Hostname
  networking.hostName = "milo";

  # Boot loader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Network manager for easy network config
  networking.networkmanager.enable = true;

  # State version - NEVER change this after initial install
  system.stateVersion = "25.11";

  # Syncthing topology configuration
  # Uncomment and configure when you're ready to set up syncthing
  # services.syncthing.settings = let
  #   topology = import ../../modules/home/syncthing-topology.nix { inherit lib; };
  #   hostname = "milo";
  #   knownDevices = topology.getDevicesForHost hostname;
  #   devices = lib.listToAttrs (map (name: {
  #     name = name;
  #     value = { id = topology.machines.${name}.deviceId; };
  #   }) knownDevices);
  #   folders = lib.mapAttrs (folderName: folderConfig: {
  #     path = "/home/weast/${folderConfig.path}";
  #     devices = topology.getDevicesForFolder hostname folderName;
  #     ignorePerms = folderConfig.ignorePerms;
  #     type = folderConfig.type or "sendreceive";
  #   } // lib.optionalAttrs (folderConfig ? patterns) {
  #     ignorePatterns = folderConfig.patterns;
  #   }) topology.sharedFolders;
  # in {
  #   inherit devices folders;
  # };
}
