# NixOS configuration for milo (home server)
{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Home Manager as NixOS module
    inputs.home-manager.nixosModules.home-manager

    # Base system configuration
    ../../modules/nixos/common.nix
    ../../modules/nixos/users.nix

    # Storage
    ../../modules/nixos/storage/btrfs-vault.nix
    ../../modules/nixos/storage/usb-mounts.nix
    ../../modules/nixos/storage/backups.nix

    # Services - comment out what you don't want yet
    ../../modules/nixos/services/jellyfin.nix
    ../../modules/nixos/services/navidrome.nix
    ../../modules/nixos/services/immich.nix
    ../../modules/nixos/services/syncthing.nix
    # ../../modules/nixos/services/docker.nix

    # Networking
    ../../modules/nixos/networking/tailscale.nix
    ../../modules/nixos/networking/avahi.nix
    # ../../modules/nixos/networking/caddy.nix  # Uncomment when you're ready to set up reverse proxy
  ];

  # Hostname
  networking.hostName = "milo";

  # Boot loader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Network manager for easy network config
  networking.networkmanager.enable = true;

  # State version - NEVER change this after initial install
  system.stateVersion = "25.11";

  # Home Manager integration
  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    extraSpecialArgs = { inherit inputs; };

    users.weast = import ./home.nix;
  };

  # Server-specific packages
  environment.systemPackages = with pkgs; [
    beets
  ];

  # Syncthing is configured in modules/nixos/services/syncthing.nix
  # All settings come from modules/home/syncthing-topology.nix
}
