# NixOS configuration for milo (home server)
{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Home Manager as NixOS module
    inputs.home-manager.nixosModules.home-manager

    # Base system configuration
    ../../modules/nixos/common.nix
    ../../modules/nixos/users.nix

    # Storage
    ../../modules/nixos/storage/btrfs-vault.nix
    ../../modules/nixos/storage/usb-mounts.nix
    ../../modules/nixos/storage/backups.nix

    # Services - comment out what you don't want yet
    ../../modules/nixos/services/jellyfin.nix
    ../../modules/nixos/services/navidrome.nix
    ../../modules/nixos/services/immich.nix
    ../../modules/nixos/services/syncthing.nix
    ../../modules/nixos/services/homepage.nix
    ../../modules/nixos/services/gitea.nix
    ../../modules/nixos/services/scanning.nix
    ../../modules/nixos/services/buero/service.nix
    ../../modules/nixos/services/paperless-ngx.nix
    # ../../modules/nixos/services/docker.nix

    # I/O devices (printers, monitors, etc.)
    ../../modules/nixos/io/cups-printing.nix

    # Networking
    ../../modules/nixos/networking/tailscale.nix
    ../../modules/nixos/networking/avahi.nix
    # ../../modules/nixos/networking/caddy.nix  # Uncomment when you're ready to set up reverse proxy
  ];

  # Hostname
  networking.hostName = "milo";

  # Boot loader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Network manager for easy network config
  networking.networkmanager.enable = true;

  # Fonts (Inter used by Büro PDF generation via WeasyPrint/fontconfig)
  fonts.packages = with pkgs; [ inter ];

  # State version - NEVER change this after initial install
  system.stateVersion = "25.11";

  # Home Manager integration
  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    extraSpecialArgs = { inherit inputs; };

    users.weast = import ./home.nix;
  };

  # Server-specific packages
  environment.systemPackages = with pkgs; [
    beets
  ];

  # Bulk storage (16TB shucked WD Elements, ext4)
  fileSystems."/mnt/bulk" = {
    device = "/dev/disk/by-uuid/da80699a-e934-4f46-b98c-1b91a45fd31f";
    fsType = "ext4";
    options = [ "defaults" "nofail" "x-systemd.device-timeout=5" ];
  };

  # Syncthing is configured in modules/nixos/services/syncthing.nix
  # All settings come from modules/home/syncthing-topology.nix
}
