# Mail tooling for the accounts in ./accounts.nix:
# mbsync fetches, notmuch indexes and tags, msmtp sends, oama refreshes OAuth
# tokens, DavMail bridges Microsoft 365. Emacs (Doom :email notmuch) reads
# ~/.config/emacs-mail/accounts.el, which is generated here too, so the Emacs
# config never names an account.
{ config, lib, pkgs, ... }:

let
  accounts = lib.attrValues config.accounts.email.accounts;
  notmuch = "${pkgs.notmuch}/bin/notmuch";

  # Providers that file sent mail themselves when you send over SMTP.
  serverSavesSent = a: lib.elem a.flavor [ "gmail.com" "outlook.office365.com" "davmail" ];

  elispString = s: "\"${lib.escape [ "\\" "\"" ] s}\"";
  addressRegexp = a: elispString (lib.escapeRegex a.address);

  accountsEl = ''
    ;;; accounts.el --- generated by home-manager (modules/home/comms/mail.nix) -*- lexical-binding: t; -*-
    ;; Do not edit; change ~/.config/nix-config/modules/home/comms/accounts.nix instead.

    ;; Where sent mail is filed (nil: the provider files it itself).
    (setq notmuch-fcc-dirs
          '(${lib.concatMapStringsSep "\n            " (a:
              "(${addressRegexp a} . ${
                if serverSavesSent a then "nil"
                else elispString "${a.name}/${a.folders.sent} +sent -inbox -unread"})")
            accounts}))

    (setq notmuch-saved-searches
          (append
           '((:name "inbox"   :query "tag:inbox" :key "i")
             (:name "unread"  :query "tag:unread and tag:inbox" :key "u")
             (:name "flagged" :query "tag:flagged" :key "f")
             (:name "sent"    :query "tag:sent" :key "t")
             (:name "drafts"  :query "tag:draft" :key "d"))
           '(${lib.concatMapStringsSep "\n             " (a:
              "(:name ${elispString "inbox/${a.name}"} :query ${elispString "tag:inbox and tag:${a.name}"})")
             accounts})))
  '';

  # Tag new mail with its account, file sent mail, then move it to the inbox.
  postNew = ''
    ${lib.concatMapStringsSep "\n" (a: ''
      ${notmuch} tag +${a.name} -- tag:new and 'path:${a.name}/**'
      ${notmuch} tag -new +sent -- tag:new and 'folder:"${a.name}/${a.folders.sent}"'
      ${notmuch} tag -new +draft -- tag:new and 'folder:"${a.name}/${a.folders.drafts}"'
      ${notmuch} tag -new +deleted -- tag:new and 'folder:"${a.name}/${a.folders.trash}"'
    '') accounts}
    ${notmuch} tag -new +inbox +unread -- tag:new
  '';

  # UserName field of the KeePassXC entry holding the Google OAuth client.
  googleClientId = pkgs.writeShellScript "google-client-id" ''
    ${pkgs.libsecret}/bin/secret-tool search Title calendar.google.com 2>&1 \
      | ${pkgs.gnused}/bin/sed -n 's/^attribute.UserName = //p'
  '';

  syncMail = pkgs.writeShellScript "sync-mail" ''
    # Keep going when one account fails (e.g. not signed in yet).
    ${config.programs.mbsync.package}/bin/mbsync --all
    status=$?
    ${notmuch} new
    exit $status
  '';
in
{
  accounts.email.maildirBasePath = "${config.xdg.dataHome}/mail";

  programs.mbsync.enable = true;
  programs.msmtp.enable = true;

  programs.notmuch = {
    enable = true;
    new.tags = [ "new" ];
    search.excludeTags = [ "deleted" "spam" ];
    hooks.postNew = postNew;
  };

  home.packages = [ pkgs.oama pkgs.libsecret ];

  # oama: OAuth2 tokens for Gmail and Outlook.com, stored in the keyring.
  # Authorize once per address: `oama authorize google <address>` /
  # `oama authorize microsoft <address>`.
  xdg.configFile."oama/config.yaml".text = ''
    encryption:
      tag: KEYRING
    services:
      google:
        client_id_cmd: |
          ${googleClientId}
        client_secret_cmd: |
          ${pkgs.libsecret}/bin/secret-tool lookup Title calendar.google.com
      microsoft:
        client_id_cmd: |
          ${pkgs.libsecret}/bin/secret-tool lookup Title oama-microsoft-client-id
        tenant: consumers
  '';

  # DavMail: IMAP/SMTP/CalDAV gateway for Microsoft 365 (McGill).
  services.davmail = {
    enable = true;
    imitateOutlook = true;
    settings = {
      "davmail.mode" = "O365Manual";
      "davmail.oauth.persistToken" = true;
    };
  };

  xdg.configFile."emacs-mail/accounts.el".text = accountsEl;

  # Fetch every 5 minutes, then index.
  systemd.user.services.sync-mail = {
    Unit.Description = "Fetch mail (mbsync) and index it (notmuch)";
    Service = {
      Type = "oneshot";
      ExecStart = "${syncMail}";
    };
  };
  systemd.user.timers.sync-mail = {
    Unit.Description = "Fetch mail every 5 minutes";
    Timer = {
      OnBootSec = "2m";
      OnUnitInactiveSec = "5m";
    };
    Install.WantedBy = [ "timers.target" ];
  };
}
