# NixOS configuration for orr (desktop workstation with AMD R9 290)
{ config, pkgs, lib, inputs, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Home Manager as NixOS module
    inputs.home-manager.nixosModules.home-manager

    # Base system configuration
    ../../modules/nixos/common.nix
    ../../modules/nixos/users.nix

    # Desktop
    ../../modules/nixos/desktop/niri.nix

    # Networking
    ../../modules/nixos/networking/tailscale.nix
    ../../modules/nixos/networking/avahi.nix
  ];

  # Hostname
  networking.hostName = "orr";

  # Boot loader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Network manager for easy network config
  networking.networkmanager.enable = true;

  # Time zone
  time.timeZone = "Europe/Berlin";

  # Locale
  i18n.defaultLocale = "en_US.UTF-8";

  # AMD CPU microcode updates
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Flatpak (system-level, needed for XDG_DATA_DIRS so launchers see Flatpak apps)
  services.flatpak.enable = true;

  # Bluetooth
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;  # GUI manager (blueman-manager / system tray)

  # Graphics (AMD R9 290)
  hardware.graphics.enable = true;
  hardware.graphics.enable32Bit = true;  # Required for Steam 32-bit games

  # Steam (must be at NixOS level for proper runtime/OpenGL setup)
  programs.steam.enable = true;

  # Enable OpenSSH daemon
  services.openssh.enable = true;

  # State version - NEVER change this after initial install
  system.stateVersion = "25.11";

  # Home Manager integration
  home-manager = {
    useGlobalPkgs = true;
    useUserPackages = true;
    extraSpecialArgs = { inherit inputs; };

    users.weast = import ./home.nix;
  };
}
